#!/usr/bin/with-contenv bash

if [ -f /usr/bin/apt ]; then
    echo "\
        python3-pip"  >> /mod-repo-packages-to-install.list
fi

echo "\
    cupy=12.2.0 \
    lxml=4.9.3  \
    rapidfuzz=3.5.2 \
    spacy_cpu_model=3.7.0 \
    spacy_trf_model=3.7.2 \
    thinc-apple-ops=0.1.4 \
    torch=2.1.1 \
    typing-extensions=4.8.0" >> /mod-pip-packages-to-install.list
